/**
* This code was generated by v0 by Vercel.
* @see https://v0.dev/t/UnOb3wiSVZg
* Documentation: https://v0.dev/docs#integrating-generated-code-into-your-nextjs-app
*/

/** Add fonts into your Next.js project:

import { Archivo } from 'next/font/google'

archivo({
  subsets: ['latin'],
  display: 'swap',
})

To read more about using these font, please visit the Next.js documentation:
- App Directory: https://nextjs.org/docs/app/building-your-application/optimizing/fonts
- Pages Directory: https://nextjs.org/docs/pages/building-your-application/optimizing/fonts
**/
import { Button } from "@/components/ui/button"
import { Label } from "@/components/ui/label"
import { Select, SelectTrigger, SelectValue, SelectContent, SelectItem } from "@/components/ui/select"
import { Card, CardContent } from "@/components/ui/card"
import {
  Dialog,
  DialogTrigger,
  DialogContent,
  DialogHeader,
  DialogTitle,
  DialogDescription,
  DialogFooter,
} from "@/components/ui/dialog";
import { Input } from "@/components/ui/input"
import { Textarea } from "@/components/ui/textarea"

export default function OrgProfile() {
  return (
    (<div className="bg-background text-foreground">
      <header className="bg-primary text-primary-foreground py-6 px-4 md:px-6">
        <div className="container mx-auto flex items-center justify-between">
          <div>
            <h1 className="text-2xl font-bold">Paws & Claws Pet Shelter</h1>
            <p className="text-sm">Helping pets find their forever homes</p>
          </div>
          <Button variant="secondary" className="hidden md:inline-flex">
            Add Pet
          </Button>
        </div>
      </header>
      <main className="container mx-auto py-12 px-4 md:px-6">
        <section className="mb-12">
          <h2 className="text-xl font-bold mb-4">Shelter Information</h2>
          <div className="grid grid-cols-1 md:grid-cols-2 gap-6">
            <div>
              <h3 className="text-lg font-semibold mb-2">Location</h3>
              <p>123 Main St, Anytown USA</p>
              <p>Anytown, CA 12345</p>
            </div>
            <div>
              <h3 className="text-lg font-semibold mb-2">Contact</h3>
              <p>Phone: (123) 456-7890</p>
              <p>Email: info@pawsandclaws.org</p>
            </div>
            <div>
              <h3 className="text-lg font-semibold mb-2">Hours</h3>
              <p>Monday - Friday: 10am - 6pm</p>
              <p>Saturday - Sunday: 12pm - 4pm</p>
            </div>
          </div>
        </section>
        <section>
          <div className="flex items-center justify-between mb-6">
            <h2 className="text-xl font-bold">Pets Available for Adoption</h2>
            <div className="flex items-center gap-2">
              <Label htmlFor="filter">Filter by:</Label>
              <Select id="filter">
                <SelectTrigger>
                  <SelectValue placeholder="Select filter" />
                </SelectTrigger>
                <SelectContent>
                  <SelectItem value="age">Age</SelectItem>
                  <SelectItem value="breed">Breed</SelectItem>
                  <SelectItem value="size">Size</SelectItem>
                </SelectContent>
              </Select>
            </div>
          </div>
          <div
            className="grid grid-cols-1 sm:grid-cols-2 md:grid-cols-3 lg:grid-cols-4 gap-6">
            <Card className="bg-card text-card-foreground">
              <img
                src="/placeholder.svg"
                width={300}
                height={200}
                alt="Pet"
                className="rounded-t-lg object-cover w-full h-48" />
              <CardContent className="p-4">
                <h3 className="text-lg font-semibold mb-2">Buddy</h3>
                <p className="text-sm text-muted-foreground mb-4">Labrador Retriever, 3 years old</p>
                <p className="text-sm">
                  Buddy is a friendly and energetic Labrador Retriever who loves to play fetch and go for long walks.
                </p>
              </CardContent>
            </Card>
            <Card className="bg-card text-card-foreground">
              <img
                src="/placeholder.svg"
                width={300}
                height={200}
                alt="Pet"
                className="rounded-t-lg object-cover w-full h-48" />
              <CardContent className="p-4">
                <h3 className="text-lg font-semibold mb-2">Bella</h3>
                <p className="text-sm text-muted-foreground mb-4">Domestic Shorthair, 1 year old</p>
                <p className="text-sm">
                  Bella is a playful and affectionate cat who loves to cuddle and explore new toys.
                </p>
              </CardContent>
            </Card>
            <Card className="bg-card text-card-foreground">
              <img
                src="/placeholder.svg"
                width={300}
                height={200}
                alt="Pet"
                className="rounded-t-lg object-cover w-full h-48" />
              <CardContent className="p-4">
                <h3 className="text-lg font-semibold mb-2">Max</h3>
                <p className="text-sm text-muted-foreground mb-4">German Shepherd, 5 years old</p>
                <p className="text-sm">
                  Max is a loyal and protective German Shepherd who loves going on hikes and playing fetch.
                </p>
              </CardContent>
            </Card>
            <Card className="bg-card text-card-foreground">
              <img
                src="/placeholder.svg"
                width={300}
                height={200}
                alt="Pet"
                className="rounded-t-lg object-cover w-full h-48" />
              <CardContent className="p-4">
                <h3 className="text-lg font-semibold mb-2">Daisy</h3>
                <p className="text-sm text-muted-foreground mb-4">Poodle, 2 years old</p>
                <p className="text-sm">
                  Daisy is a friendly and intelligent Poodle who loves to learn new tricks and cuddle with her owners.
                </p>
              </CardContent>
            </Card>
          </div>
        </section>
      </main>
      <Dialog>
        <DialogTrigger asChild>
          <Button className="fixed bottom-6 right-6 md:hidden">Add Pet</Button>
        </DialogTrigger>
        <DialogContent className="bg-card text-card-foreground p-6 rounded-lg max-w-2xl">
          <DialogHeader>
            <DialogTitle>Add a New Pet</DialogTitle>
            <DialogDescription>Fill out the form below to add a new pet to the shelter.</DialogDescription>
          </DialogHeader>
          <div>
            <form className="grid grid-cols-1 sm:grid-cols-2 gap-6">
              <div className="grid gap-2">
                <Label htmlFor="name">Name</Label>
                <Input id="name" placeholder="Enter pet's name" />
              </div>
              <div className="grid gap-2">
                <Label htmlFor="breed">Breed</Label>
                <Input id="breed" placeholder="Enter pet's breed" />
              </div>
              <div className="grid gap-2">
                <Label htmlFor="age">Age</Label>
                <Input id="age" type="number" placeholder="Enter pet's age" />
              </div>
              <div className="grid gap-2">
                <Label htmlFor="size">Size</Label>
                <Select id="size">
                  <SelectTrigger>
                    <SelectValue placeholder="Select pet's size" />
                  </SelectTrigger>
                  <SelectContent>
                    <SelectItem value="small">Small</SelectItem>
                    <SelectItem value="medium">Medium</SelectItem>
                    <SelectItem value="large">Large</SelectItem>
                  </SelectContent>
                </Select>
              </div>
              <div className="grid gap-2 col-span-2">
                <Label htmlFor="description">Description</Label>
                <Textarea
                  id="description"
                  rows={3}
                  placeholder="Enter a short description of the pet" />
              </div>
              <div className="col-span-2">
                <Label htmlFor="image">Upload Image</Label>
                <Input id="image" type="file" />
              </div>
            </form>
          </div>
          <DialogFooter>
            <Button>Save Pet</Button>
            <div>
              <Button variant="secondary">Cancel</Button>
            </div>
          </DialogFooter>
        </DialogContent>
      </Dialog>
    </div>)
  );
}
